# Generated by Django 4.2 on 2024-10-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collction',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='collction',
            new_name='collection',
        ),
    ]
