# Generated by Django 4.2 on 2024-03-17 20:20

from django.db import migrations


collection_sql = open("shop/data/collection.sql", encoding="utf8")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(collection_sql)
    ]
