# Generated by Django 4.2 on 2024-03-17 20:20

from django.db import migrations


category_sql = open("shop/data/category.sql", encoding="utf8")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_collection'),
    ]

    operations = [
        migrations.RunSQL(category_sql)
    ]
